In [ ]:
#ARCHIVO PARA LA COMUNICACIÓN SERIAL ENTRE EL CIRCUITO Y EL CÓDIGO

#%%
from joblib import load
import pandas as pd
import tensorflow as tf
import matplotlib.pyplot as plt
import numpy as np
import serial  # PARA LA COMUNICACIÓN SERIAL

#Carga de datos de entrenamiento para calcular la media y el estándar
train_x = np.load('c:\\Users\\Indatech\\Downloads\\EMG\\train_x.npy')

In [ ]:
#%%

# PARA NORMALIZAR
mean = train_x.mean(axis=0)
std = train_x.std(axis=0)

In [ ]:
#%%

#Cargando modelo KNN
KNN_model = load('c:\\Users\\Indatech\\Downloads\\EMG\\knn_model.joblib')

#ser = serial.Serial('COM4', 9600) 

arduino = serial.Serial(port='COM3', baudrate=9600, timeout=.1) 

In [ ]:
# PRUEBA #1 

# PREDICTIONS:
    #0 - Unknown,
    #1 - hand at rest,
    #2 - hand clenched in a fist,
    #3 - wrist flexion,
    #4 – wrist extension

positions = ['Mano en reposo', 'Mano en puño', 'Flexión de muñeca', 'Extensión de muñeca']

i = 0
while True:
    # Lectura de datos EMG sin procesar desde el puerto serial
    raw_data = arduino.readline()
    
    print('Data no procesada: ', raw_data)

    # Preprocesando la data
    arduino_to_str = raw_data.decode('utf-8')
    str_to_list = arduino_to_str.split(",") #Separa la cadena en una lista de valores basada en las comas
    voltage = str_to_list[1]  #Extrayendo el valor que quiero (los otros son el rango 1-5 V)
    voltage = float(voltage)  #Convertir de str a float
    voltage = voltage*0.01
    print('Voltaje: ', voltage)

    # Poniendo en el formato que necesitamos para hacer la predicción
    voltage_array = np.repeat(voltage, 4) # 4 canales
    print(voltage_array)
    voltage_array = np.reshape(voltage_array, (1,4))
    voltage_array -= mean
    voltage_array /= std

    print(voltage_array)

    if voltage == 0.0:
        print('Predicción: No hay movimiento')  #AJUSTE MANUAL
    # Realizando la prediccion
    prediction = KNN_model.predict(voltage_array)  # Predice usando el modelo cargado

    # Salida
    if prediction[0] != 0 :
        print('Predicción: ', positions[prediction[0]-1])  
    else:
        print('Predicción: ', positions[prediction[0]])

    i = i+1
    #if i > 45:
     #   x = input('Continuar con la adquisición de señales?  (S/N) ')
      #  if x.lower() == 'n':
       #     break

Data no procesada:  b'52751,   4.8, 0.0, 5.0\r\n'
Voltaje:  0.0048
[0.0048 0.0048 0.0048 0.0048]
[[24.44642212 33.82310399 34.35188856 17.67685398]]
Predicción:  Flexión de muñeca
Data no procesada:  b'252852,   0.0, 0.0, 5.0\r\n'
Voltaje:  0.0
[0. 0. 0. 0.]
[[0.03990693 0.06840944 0.06887786 0.03405864]]
Predicción: No hay movimiento
Predicción:  Mano en reposo
Data no procesada:  b'252952,   4.4, 0.0, 5.0\r\n'
Voltaje:  0.0044
[0.0044 0.0044 0.0044 0.0044]
[[22.41254585 31.01021278 31.49497101 16.20662103]]
Predicción:  Flexión de muñeca
Data no procesada:  b'253052,   4.6, 0.0, 5.0\r\n'
Voltaje:  0.0046
[0.0046 0.0046 0.0046 0.0046]
[[23.42948399 32.41665839 32.92342979 16.94173751]]
Predicción:  Flexión de muñeca
Data no procesada:  b'253154,   4.9, 0.0, 5.0\r\n'
Voltaje:  0.004900000000000001
[0.0049 0.0049 0.0049 0.0049]
[[24.95489119 34.5263268  35.06611795 18.04441222]]
Predicción:  Flexión de muñeca
Data no procesada:  b'253254,   4.8, 0.0, 5.0\r\n'
Voltaje:  0.0048
[0.0048 0.

ValueError: could not convert string to float: '   4.44.7'

In [ ]:
#PRUEBA #2

# PREDICTIONS:
    #0 - Unknown,
    #1 - hand at rest,
    #2 - hand clenched in a fist,
    #3 - wrist flexion,
    #4 – wrist extension

positions = ['Mano en reposo', 'Mano en puño', 'Flexión de muñeca', 'Extensión de muñeca']

i = 0
while True:
    # Read raw EMG data from serial port
    raw_data = arduino.readline()
    
    print('Data no procesada: ', raw_data)

    # Preprocessing data
    arduino_to_str = raw_data.decode('utf-8')
    str_to_list = arduino_to_str.split(",") #Separa la cadena en una lista de valores basada en las comas
    voltage = str_to_list[1]  #Extrayendo el valor que quiero (los otros son el rango 1-5 V)
    voltage = float(voltage)  #Convertir de str a float
    voltage = voltage*0.01
    print('Voltaje: ', voltage)

    # Poniendo en el formato que necesitamos para hacer la predicción
    voltage_array = np.repeat(voltage, 4) # 4 canales
    print(voltage_array)
    voltage_array = np.reshape(voltage_array, (1,4))
    voltage_array -= mean
    voltage_array /= std

    print(voltage_array)

    if voltage == 0.0:
        print('Predicción: No hay movimiento')  #AJUSTE MANUAL
    # Make prediction
    prediction = KNN_model.predict(voltage_array)  # Predice usando el modelo cargado

    # Salida
    if prediction[0] != 0 :
        print('Predicción: ', positions[prediction[0]-1])  
    else:
        print('Predicción: ', positions[prediction[0]])

    i = i+1
    #if i > 45:
     #   x = input('Continuar con la adquisición de señales?  (S/N) ')
      #  if x.lower() == 'n':
       #     break

Data no procesada:  b'85331,   0.0, 0.0, 5.0\r\n'
Voltaje:  0.0
[0. 0. 0. 0.]
[[0.03990693 0.06840944 0.06887786 0.03405864]]
Predicción: No hay movimiento
Predicción:  Mano en reposo
Data no procesada:  b'485432,   0.0, 0.0, 5.0\r\n'
Voltaje:  0.0
[0. 0. 0. 0.]
[[0.03990693 0.06840944 0.06887786 0.03405864]]
Predicción: No hay movimiento
Predicción:  Mano en reposo
Data no procesada:  b'485533,   0.0, 0.0, 5.0\r\n'
Voltaje:  0.0
[0. 0. 0. 0.]
[[0.03990693 0.06840944 0.06887786 0.03405864]]
Predicción: No hay movimiento
Predicción:  Mano en reposo
Data no procesada:  b'485634,   0.0, 0.0, 5.0\r\n'
Voltaje:  0.0
[0. 0. 0. 0.]
[[0.03990693 0.06840944 0.06887786 0.03405864]]
Predicción: No hay movimiento
Predicción:  Mano en reposo
Data no procesada:  b'485734,   0.5, 0.0, 5.0\r\n'
Voltaje:  0.005
[0.005 0.005 0.005 0.005]
[[25.46336025 35.2295496  35.78034734 18.41197045]]
Predicción:  Flexión de muñeca
Data no procesada:  b'485834,   4.7, 0.0, 5.0\r\n'
Voltaje:  0.047
[0.047 0.047 0.047

KeyboardInterrupt: 

In [ ]:
# PRUEBA #3

# PREDICTIONS:
    #0 - Unknown,
    #1 - hand at rest,
    #2 - hand clenched in a fist,
    #3 - wrist flexion,
    #4 – wrist extension

positions = ['Mano en reposo', 'Mano en puño', 'Flexión de muñeca', 'Extensión de muñeca']

i = 0
while True:
    # Read raw EMG data from serial port
    raw_data = arduino.readline()
    
    print('Data no procesada: ', raw_data)

    # Preprocessing data
    arduino_to_str = raw_data.decode('utf-8')
    str_to_list = arduino_to_str.split(",") #Separa la cadena en una lista de valores basada en las comas
    voltage = str_to_list[1]  #Extrayendo el valor que quiero (los otros son el rango 1-5 V)
    voltage = float(voltage)  #Convertir de str a float
    voltage = voltage*0.01
    print('Voltaje: ', voltage)

    # Poniendo en el formato que necesitamos para hacer la predicción
    voltage_array = np.repeat(voltage, 4) # 4 canales
    print(voltage_array)
    voltage_array = np.reshape(voltage_array, (1,4))
    voltage_array -= mean
    voltage_array /= std

    print(voltage_array)

    if voltage == 0.0:
        print('Predicción: No hay movimiento')  #AJUSTE MANUAL
    # Make prediction
    prediction = KNN_model.predict(voltage_array)  # Predice usando el modelo cargado

    # Salida
    if prediction[0] != 0 :
        print('Predicción: ', positions[prediction[0]-1])  
    else:
        print('Predicción: ', positions[prediction[0]])

    i = i+1
    #if i > 45:
     #   x = input('Continuar con la adquisición de señales?  (S/N) ')
      #  if x.lower() == 'n':
       #     break

Data no procesada:  b'  0.0, 0.0, 5.0\r\n'
Voltaje:  0.0
[0. 0. 0. 0.]
[[0.03990693 0.06840944 0.06887786 0.03405864]]
Predicción: No hay movimiento
Predicción:  Mano en reposo
Data no procesada:  b'566543,   0.0, 0.0, 5.0\r\n'
Voltaje:  0.0
[0. 0. 0. 0.]
[[0.03990693 0.06840944 0.06887786 0.03405864]]
Predicción: No hay movimiento
Predicción:  Mano en reposo
Data no procesada:  b'566644,   0.0, 0.0, 5.0\r\n'
Voltaje:  0.0
[0. 0. 0. 0.]
[[0.03990693 0.06840944 0.06887786 0.03405864]]
Predicción: No hay movimiento
Predicción:  Mano en reposo
Data no procesada:  b'566745,   0.0, 0.0, 5.0\r\n'
Voltaje:  0.0
[0. 0. 0. 0.]
[[0.03990693 0.06840944 0.06887786 0.03405864]]
Predicción: No hay movimiento
Predicción:  Mano en reposo
Data no procesada:  b'566845,   0.0, 0.0, 5.0\r\n'
Voltaje:  0.0
[0. 0. 0. 0.]
[[0.03990693 0.06840944 0.06887786 0.03405864]]
Predicción: No hay movimiento
Predicción:  Mano en reposo
Data no procesada:  b'566945,   0.0, 0.0, 5.0\r\n'
Voltaje:  0.0
[0. 0. 0. 0.]
[[0.

KeyboardInterrupt: 